# Generated by Django 6.0.2 on 2026-03-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionitem',
            name='completion_percentage',
        ),
        migrations.AddField(
            model_name='actionitem',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
