# Generated by Django 6.0.2 on 2026-03-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_company_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user can manage the company.'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['domain'], name='accounts_co_domain_483fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active'], name='accounts_co_is_acti_4abc2f_idx'),
        ),
    ]
