# Generated by Django 6.0.2 on 2026-03-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_company_domain_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr_manager', 'HR Manager'), ('accountant', 'Accountant'), ('manager', 'Manager'), ('secretary', 'Secretary'), ('employee', 'Employee')], default='employee', help_text='User role for access control', max_length=20),
        ),
    ]
