# Generated by Django 6.0.2 on 2026-03-09 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s\\-().]{7,20}$', 'Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_company_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user can manage company settings.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s\\-().]{7,20}$', 'Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr_manager', 'HR Manager'), ('accountant', 'Accountant'), ('manager', 'Manager'), ('secretary', 'Secretary'), ('employee', 'Employee')], db_index=True, default='employee', help_text='User role for access control.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['company', 'role'], name='accounts_us_company_8958d5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['company', 'is_active'], name='accounts_us_company_ff0051_idx'),
        ),
    ]
