# Generated by Django 6.0.2 on 2026-03-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_last_login_ip_alter_company_company_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr_manager', 'HR Manager'), ('accountant', 'Accountant'), ('manager', 'Manager'), ('secretary', 'Secretary'), ('stock_manager', 'Stock Manager'), ('employee', 'Employee')], db_index=True, default='employee', help_text='User role for access control.', max_length=20),
        ),
    ]
