# Generated by Django 6.0.2 on 2026-08-02 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_invitation_remove_company_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.CharField(max_length=255)),
                ('email_host_password', models.CharField(max_length=255)),
                ('default_from_email', models.EmailField(default='no-reply@zentral.com', max_length=254)),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Company Email Settings',
                'verbose_name_plural': 'Company Email Settings',
            },
        ),
    ]
