# Generated by Django 6.0.2 on 2026-08-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_companyemailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mtn_momo_number',
            field=models.CharField(blank=True, help_text='MTN Mobile Money transaction number for client payments', max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='orange_money_number',
            field=models.CharField(blank=True, help_text='Orange Money transaction number for client payments', max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp contact number for marketplace clients (e.g. +2376XXXXXXXX)', max_length=30),
        ),
    ]
