# Generated by Django 6.0.2 on 2026-09-20 10:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_company_mtn_momo_number_company_orange_money_number_and_more'),
        ('employees', '0007_employee_names_optional_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s\\-().]{5,20}$', 'Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s\\-().]{5,20}$', 'Enter a valid phone number.')]),
        ),
    ]
