# Generated by Django 6.0.2 on 2026-09-17 06:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_company_mtn_momo_number_company_orange_money_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(blank=True, max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='accounts.company')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['company', 'module', 'action'], name='governance__company_280960_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('capability', models.CharField(choices=[('employees.view', 'employees.view'), ('employees.manage', 'employees.manage'), ('finance.view', 'finance.view'), ('finance.manage', 'finance.manage'), ('finance.post_journal', 'finance.post_journal'), ('finance.reverse_journal', 'finance.reverse_journal'), ('inventory.view', 'inventory.view'), ('inventory.manage', 'inventory.manage'), ('inventory.issue', 'inventory.issue'), ('procurement.view', 'procurement.view'), ('procurement.manage', 'procurement.manage'), ('procurement.approve', 'procurement.approve'), ('hr.view', 'hr.view'), ('hr.manage', 'hr.manage'), ('hr.manage_payroll', 'hr.manage_payroll'), ('crm.view', 'crm.view'), ('crm.manage', 'crm.manage'), ('projects.view', 'projects.view'), ('projects.manage', 'projects.manage'), ('approvals.decide', 'approvals.decide'), ('reporting.view', 'reporting.view'), ('reporting.export', 'reporting.export'), ('admin.manage_users', 'admin.manage_users'), ('admin.manage_roles', 'admin.manage_roles'), ('admin.manage_organisation', 'admin.manage_organisation')], max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_capabilities', to='accounts.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'role'], name='governance__company_84579e_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'role', 'capability'), name='unique_role_capability')],
            },
        ),
        migrations.CreateModel(
            name='UserCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(choices=[('employees.view', 'employees.view'), ('employees.manage', 'employees.manage'), ('finance.view', 'finance.view'), ('finance.manage', 'finance.manage'), ('finance.post_journal', 'finance.post_journal'), ('finance.reverse_journal', 'finance.reverse_journal'), ('inventory.view', 'inventory.view'), ('inventory.manage', 'inventory.manage'), ('inventory.issue', 'inventory.issue'), ('procurement.view', 'procurement.view'), ('procurement.manage', 'procurement.manage'), ('procurement.approve', 'procurement.approve'), ('hr.view', 'hr.view'), ('hr.manage', 'hr.manage'), ('hr.manage_payroll', 'hr.manage_payroll'), ('crm.view', 'crm.view'), ('crm.manage', 'crm.manage'), ('projects.view', 'projects.view'), ('projects.manage', 'projects.manage'), ('approvals.decide', 'approvals.decide'), ('reporting.view', 'reporting.view'), ('reporting.export', 'reporting.export'), ('admin.manage_users', 'admin.manage_users'), ('admin.manage_roles', 'admin.manage_roles'), ('admin.manage_organisation', 'admin.manage_organisation')], max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_capabilities', to='accounts.company')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'user'], name='governance__company_0e1371_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'capability'), name='unique_user_capability')],
            },
        ),
    ]
