# Generated by Django 6.0.2 on 2026-09-17 07:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_company_mtn_momo_number_company_orange_money_number_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('governance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('role', models.CharField(blank=True, max_length=30)),
                ('capability', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('approval_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('required', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.AlterField(
            model_name='rolecapability',
            name='capability',
            field=models.CharField(choices=[('employees.view', 'employees.view'), ('employees.manage', 'employees.manage'), ('finance.view', 'finance.view'), ('finance.manage', 'finance.manage'), ('finance.post_journal', 'finance.post_journal'), ('finance.reverse_journal', 'finance.reverse_journal'), ('inventory.view', 'inventory.view'), ('inventory.manage', 'inventory.manage'), ('inventory.issue', 'inventory.issue'), ('procurement.view', 'procurement.view'), ('procurement.manage', 'procurement.manage'), ('procurement.approve', 'procurement.approve'), ('hr.view', 'hr.view'), ('hr.manage', 'hr.manage'), ('hr.manage_payroll', 'hr.manage_payroll'), ('crm.view', 'crm.view'), ('crm.manage', 'crm.manage'), ('projects.view', 'projects.view'), ('projects.manage', 'projects.manage'), ('approvals.decide', 'approvals.decide'), ('reporting.view', 'reporting.view'), ('reporting.export', 'reporting.export'), ('admin.manage_users', 'admin.manage_users'), ('admin.manage_roles', 'admin.manage_roles'), ('admin.manage_organisation', 'admin.manage_organisation'), ('finance.approve_payment', 'finance.approve_payment')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usercapability',
            name='capability',
            field=models.CharField(choices=[('employees.view', 'employees.view'), ('employees.manage', 'employees.manage'), ('finance.view', 'finance.view'), ('finance.manage', 'finance.manage'), ('finance.post_journal', 'finance.post_journal'), ('finance.reverse_journal', 'finance.reverse_journal'), ('inventory.view', 'inventory.view'), ('inventory.manage', 'inventory.manage'), ('inventory.issue', 'inventory.issue'), ('procurement.view', 'procurement.view'), ('procurement.manage', 'procurement.manage'), ('procurement.approve', 'procurement.approve'), ('hr.view', 'hr.view'), ('hr.manage', 'hr.manage'), ('hr.manage_payroll', 'hr.manage_payroll'), ('crm.view', 'crm.view'), ('crm.manage', 'crm.manage'), ('projects.view', 'projects.view'), ('projects.manage', 'projects.manage'), ('approvals.decide', 'approvals.decide'), ('reporting.view', 'reporting.view'), ('reporting.export', 'reporting.export'), ('admin.manage_users', 'admin.manage_users'), ('admin.manage_roles', 'admin.manage_roles'), ('admin.manage_organisation', 'admin.manage_organisation'), ('finance.approve_payment', 'finance.approve_payment')], max_length=100),
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned for correction'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='accounts.company')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned for correction')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='governance.approvalrequest')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='governance.approvalstep')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('transaction_type', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('applies_from', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('applies_to', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('allow_self_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='accounts.company')),
            ],
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='governance.approvalworkflow'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='governance.approvalworkflow'),
        ),
        migrations.AddConstraint(
            model_name='approvalworkflow',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_approval_workflow_name'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.UniqueConstraint(fields=('workflow', 'sequence'), name='unique_approval_step_sequence'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['company', 'status'], name='governance__company_9470f7_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['content_type', 'object_id'], name='governance__content_73c775_idx'),
        ),
    ]
