# Generated by Django 6.0.2 on 2026-03-12 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_department_updated_at_alter_employee_photo_and_more'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, help_text='HR job position/grade for this employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.position'),
        ),
    ]
