# Generated by Django 6.0.2 on 2026-03-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('developer', 'Developer'), ('designer', 'Designer'), ('analyst', 'Analyst'), ('engineer', 'Engineer'), ('intern', 'Intern'), ('hr', 'Human Resource'), ('accountant', 'Accountant'), ('secretary', 'Secretary'), ('project_manager', 'Project Manager'), ('stock_manager', 'Stock Manager'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
    ]
