# Generated by Django 6.0.2 on 2026-09-20 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_user_names_to_employees(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    for employee in Employee.objects.select_related('user').all():
        if employee.user_id:
            employee.first_name = employee.user.first_name
            employee.last_name = employee.user.last_name
            employee.save(update_fields=['first_name', 'last_name'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(copy_user_names_to_employees, noop_reverse),
    ]
