# Generated by Django 6.0.2 on 2026-09-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_names_optional_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_identification_number',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
