# Generated by Django 6.0.2 on 2026-09-25 14:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_access_controlled'),
        ('employees', '0008_employee_bank_account_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=160)),
                ('asset_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('phone', 'Phone'), ('tablet', 'Tablet'), ('vehicle', 'Vehicle'), ('equipment', 'Equipment'), ('other', 'Other')], default='other', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'In maintenance'), ('retired', 'Retired'), ('lost', 'Lost')], db_index=True, default='available', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_company_assets', to='employees.employee')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_company_assets', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_assets', to='accounts.company')),
            ],
            options={
                'ordering': ['name', 'asset_tag'],
                'indexes': [models.Index(fields=['company', 'status'], name='employees_c_company_c74278_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'asset_tag'), name='unique_company_asset_tag')],
            },
        ),
    ]
