# Generated by Django 6.0.2 on 2026-09-17 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_company_mtn_momo_number_company_orange_money_number_and_more'),
        ('employees', '0006_alter_employee_role'),
        ('hr', '0005_skill_employeeskill_trainingcourse_trainingsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('leave', 'On Leave')], default='present', max_length=20)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('early_leave_minutes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'attendance_date'], name='hr_attendan_company_d4429b_idx'), models.Index(fields=['employee', 'attendance_date'], name='hr_attendan_employe_db65ed_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'employee', 'attendance_date'), name='unique_employee_attendance_day')],
            },
        ),
    ]
