# Generated by Django 6.0.2 on 2026-09-22 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_supplierinvoice_purchase_order'),
        ('hr', '0007_applicant_benefitplan_disciplinarycase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiod',
            name='finance_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_periods', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='posted_to_finance',
            field=models.BooleanField(default=False),
        ),
    ]
