# Generated by Django 6.0.2 on 2026-09-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_payrollperiod_finance_journal_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('identity', 'Identity'), ('contract', 'Contract'), ('certificate', 'Certificate'), ('policy', 'Policy'), ('medical', 'Medical'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
