# Generated by Django 6.0.2 on 2026-09-25 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_alter_employeedocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancegoal',
            name='achieved_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='performancegoal',
            name='achievement_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='performancegoal',
            name='evidence',
            field=models.FileField(blank=True, upload_to='hr/performance-evidence/'),
        ),
        migrations.AddField(
            model_name='performancegoal',
            name='target_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='performancegoal',
            name='unit',
            field=models.CharField(blank=True, help_text='Examples: members, installations, projects, MWK', max_length=80),
        ),
        migrations.AlterField(
            model_name='performancegoal',
            name='progress',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
