# Generated by Django 6.0.2 on 2026-08-03 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_companyemailsettings'),
        ('marketplace', '0007_returnrequest_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_publishable_key', models.CharField(default='', blank=True, help_text='Stripe Publishable Key (starts with pk_)', max_length=255)),
                ('stripe_secret_key', models.CharField(default='', blank=True, help_text='Stripe Secret Key (starts with sk_)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Company Payment Settings',
                'verbose_name_plural': 'Company Payment Settings',
            },
        ),
    ]
