# Generated by Django 6.0.2 on 2026-08-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_companypaymentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypaymentsettings',
            name='flutterwave_public_key',
            field=models.CharField(default='', blank=True, help_text='Flutterwave Public Key (starts with FLWPUBK_)', max_length=255),
        ),
        migrations.AddField(
            model_name='companypaymentsettings',
            name='flutterwave_secret_key',
            field=models.CharField(default='', blank=True, help_text='Flutterwave Secret Key (starts with FLWSECK_)', max_length=255),
        ),
    ]
