# Generated by Django 6.0.2 on 2026-08-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_companypaymentsettings_flutterwave_public_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypaymentsettings',
            name='flutterwave_public_key',
        ),
        migrations.RemoveField(
            model_name='companypaymentsettings',
            name='flutterwave_secret_key',
        ),
        migrations.RemoveField(
            model_name='companypaymentsettings',
            name='stripe_publishable_key',
        ),
        migrations.RemoveField(
            model_name='companypaymentsettings',
            name='stripe_secret_key',
        ),
        migrations.AddField(
            model_name='companypaymentsettings',
            name='mtn_momo_number',
            field=models.CharField(blank=True, default='', help_text='MTN Mobile Money transfer number', max_length=50),
        ),
        migrations.AddField(
            model_name='companypaymentsettings',
            name='orange_money_number',
            field=models.CharField(blank=True, default='', help_text='Orange Money transfer number', max_length=50),
        ),
        migrations.AddField(
            model_name='companypaymentsettings',
            name='payment_instructions',
            field=models.TextField(blank=True, default='', help_text='Payment instructions displayed to customers during checkout'),
        ),
        migrations.AddField(
            model_name='companypaymentsettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', help_text='WhatsApp contact number for payments (e.g., +237690000000)', max_length=50),
        ),
    ]
