# Generated by Django 6.0.2 on 2026-02-12 15:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_salary'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soustache',
            name='completion_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='soustache',
            name='duree_estimee',
            field=models.IntegerField(default=0, help_text='Durée estimée en heures', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
