# Generated by Django 6.0.2 on 2026-03-11 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_last_login_ip_alter_company_company_password_and_more'),
        ('employees', '0004_alter_department_updated_at_alter_employee_photo_and_more'),
        ('projects', '0002_soustache_completion_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='planning', max_length=20),
        ),
        migrations.AlterField(
            model_name='soustache',
            name='duree_estimee',
            field=models.PositiveIntegerField(default=0, help_text='Durée estimée en heures'),
        ),
        migrations.AlterField(
            model_name='soustache',
            name='ordre',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='soustache',
            name='status',
            field=models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('en_attente', 'En attente'), ('annule', 'Annulé')], db_index=True, default='a_faire', max_length=20),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'status'], name='projects_pr_company_48dbe1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'priority'], name='projects_pr_company_c19b78_idx'),
        ),
        migrations.AddIndex(
            model_name='soustache',
            index=models.Index(fields=['projet', 'status'], name='projects_so_projet__32755c_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_project_name_per_company'),
        ),
    ]
