# Generated by Django 6.0.2 on 2026-09-22 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_marketplacefinancesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='reportline',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_lines', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='reportline',
            name='line_type',
            field=models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense'), ('header', 'Header'), ('subtotal', 'Subtotal'), ('total', 'Total'), ('net_income', 'Net Income'), ('operating', 'Operating'), ('net_change', 'Net Change')], max_length=20),
        ),
    ]
