# Generated by Django 6.0.2 on 2026-09-22 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_journalentry_reversed_entry_journalentry_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryline',
            name='posted_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_line', to='finance.transaction'),
        ),
    ]
