# Generated by Django 6.0.2 on 2026-09-22 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_journalentryline_posted_transaction'),
        ('procurement', '0003_purchaseorder_requested_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_invoices', to='procurement.purchaseorder'),
        ),
    ]
