# Generated by Django 6.0.2 on 2026-04-17 09:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_leave_requests', models.BooleanField(default=True)),
                ('email_performance_reviews', models.BooleanField(default=True)),
                ('email_training_updates', models.BooleanField(default=True)),
                ('email_payroll_updates', models.BooleanField(default=True)),
                ('email_meeting_invitations', models.BooleanField(default=True)),
                ('email_system_alerts', models.BooleanField(default=True)),
                ('in_app_leave_requests', models.BooleanField(default=True)),
                ('in_app_performance_reviews', models.BooleanField(default=True)),
                ('in_app_training_updates', models.BooleanField(default=True)),
                ('in_app_payroll_updates', models.BooleanField(default=True)),
                ('in_app_meeting_invitations', models.BooleanField(default=True)),
                ('in_app_system_alerts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('leave_request', 'Leave Request Submitted'), ('leave_approved', 'Leave Request Approved'), ('leave_denied', 'Leave Request Denied'), ('performance_review', 'Performance Review'), ('performance_goal', 'Performance Goal Update'), ('training_enrollment', 'Training Enrollment'), ('training_completed', 'Training Completed'), ('payroll_processed', 'Payroll Processed'), ('meeting_invitation', 'Meeting Invitation'), ('project_update', 'Project Update'), ('crm_opportunity', 'CRM Opportunity'), ('inventory_low', 'Low Inventory Alert'), ('marketplace_order', 'Marketplace Order'), ('system_alert', 'System Alert')], default='system_alert', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_8a7c6b_idx'), models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_f77590_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
