# Generated by Django 6.0.2 on 2026-04-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('leave_request', 'Leave Request Submitted'), ('leave_approved', 'Leave Request Approved'), ('leave_denied', 'Leave Request Denied'), ('performance_review', 'Performance Review'), ('performance_goal', 'Performance Goal Update'), ('training_enrollment', 'Training Enrollment'), ('training_completed', 'Training Completed'), ('payroll_processed', 'Payroll Processed'), ('meeting_invitation', 'Meeting Invitation'), ('meeting_scheduled', 'Meeting Scheduled'), ('action_item_assigned', 'Action Item Assigned'), ('action_item_completed', 'Action Item Completed'), ('project_update', 'Project Update'), ('crm_opportunity', 'CRM Opportunity'), ('inventory_low', 'Low Inventory Alert'), ('marketplace_order', 'Marketplace Order'), ('system_alert', 'System Alert')], default='system_alert', max_length=50),
        ),
    ]
