# Generated by Django 6.0.2 on 2026-03-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/'),
        ),
    ]
