# Generated by Django 6.0.2 on 2026-03-20 18:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stock_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='stock',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_marketplace_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
