# Generated by Django 6.0.2 on 2026-04-20 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20260320_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, help_text='Cost price for inventory', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='is_marketplace_visible',
            field=models.BooleanField(default=True, help_text='Show this item on the marketplace'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price for marketplace', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
