# Generated by Django 6.0.2 on 2026-09-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('returned', 'Returned for correction'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partially_received', 'Partially received'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=25),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('returned', 'Returned for correction'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted')], db_index=True, default='draft', max_length=20),
        ),
    ]
