# Generated by Django 6.0.2 on 2026-03-11 22:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_last_login_ip_alter_company_company_password_and_more'),
        ('crm', '0001_initial'),
        ('employees', '0004_alter_department_updated_at_alter_employee_photo_and_more'),
        ('marketplace', '0002_alter_client_unique_together_remove_order_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('note', 'Note'), ('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('other', 'Other')], default='note', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='marketplace_client',
            field=models.OneToOneField(blank=True, help_text='Link this contact to an existing marketplace client account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_contact', to='marketplace.client'),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunities', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='follow_up_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='prospect', max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company', 'organization'], name='crm_contact_company_82a301_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['company', 'stage'], name='crm_opportu_company_1121c7_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['follow_up_date'], name='crm_opportu_follow__9efc56_idx'),
        ),
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_notes', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.contact'),
        ),
    ]
