# Generated by Django 6.0.2 on 2026-05-04 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_last_seen'),
        ('crm', '0002_note_contact_marketplace_client_contact_updated_at_and_more'),
        ('employees', '0006_alter_employee_role'),
        ('finance', '0005_marketplacefinancesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='revenue_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_opportunity', to='finance.transaction'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['company', 'payment_status'], name='crm_opportu_company_55d303_idx'),
        ),
    ]
